### ISSUE TITLE
Right presets are not shown when developing locally anymore

### ISSUE THREAD

**Issue by danielstorch** [Mistralys/application-framework#67]
Currently user roles (right presets) for testing locally are not rendered in the menu anymore.

I was able to fix this by removing the `if(!$user instanceof Application_User_Extended)` condition here: `src/classes/Application/Session/Base.php -> initRightPresets()`.

Hopefully this helps finding/fixing the issue.

**Comment by Mistralys** [comment]
This has been fixed in the current state. The session handling of the presets and the developer mode had to be updated, as they did not work as intended.
